### PR TITLE
Issue #86 + Replaced Maakaf with its Icon PR

### PR DESCRIPTION
**Pull request by Senior-ai**
I honestly dont know why in the PR it says I rewrote Header.astro with the same lines but whatever
@UrielOfir I assume the project isn't really in use as there is another web app and a landing page to the community - let me know what do you think about it

### CODE REVIEW

**Comment by UrielOfir** [comment]
The logs.
Can you fix the PR?

Screenshot from 2023-12-19 13-22-45

**Comment by Senior-ai** [comment]
> The logs. @Senior-ai Can you fix the PR?
> 
> Screenshot from 2023-12-19 13-22-45

Im so confused, I tried to reinstall pnpm so there wont be a mismatch but still no success. for some reason it happens with flag-icons specifically. tried different approaches, if you are familliar with this pnpm issue  let me know

**Comment by Senior-ai** [comment]
Fixed i t(: @UrielOfir

**Comment by UrielOfir** [comment]
Great work!

**Review by UrielOfir — APPROVED** [review]

**Pull request merged**
